import React, { useState } from 'react';
import { ElevatorConfig, ConfigSection } from './types';
import { INITIAL_CONFIG } from './constants';
import { Preview3D } from './components/Preview3D';
import { Controls } from './components/Controls';
import { generateElevatorRender } from './services/geminiService';
import { X, ChevronLeft, Download } from 'lucide-react';

const App: React.FC = () => {
  const [config, setConfig] = useState<ElevatorConfig>(INITIAL_CONFIG);
  const [activeSection, setActiveSection] = useState<ConfigSection>('walls');
  const [aiImage, setAiImage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showAiModal, setShowAiModal] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateAI = async () => {
    setIsGenerating(true);
    setError(null);
    try {
      const imageUrl = await generateElevatorRender(config);
      setAiImage(imageUrl);
      setShowAiModal(true);
    } catch (err) {
      setError("Failed to generate image. Please check API key and try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="flex h-screen w-screen bg-gray-950 text-white font-sans overflow-hidden">
      
      {/* LEFT: VISUAL PREVIEW AREA */}
      <main className="flex-1 relative flex flex-col">
        {/* Top Bar */}
        <header className="absolute top-0 left-0 right-0 z-20 p-6 flex justify-between items-start pointer-events-none">
          <div className="bg-black/40 backdrop-blur-md p-4 rounded-lg border border-white/10 pointer-events-auto">
            <h1 className="text-2xl font-bold tracking-tight text-white">LIFT<span className="text-blue-500">DESIGNER</span></h1>
            <p className="text-xs text-gray-400 mt-1">Passenger Elevator Configurator v1.0</p>
          </div>
          
          <div className="bg-black/40 backdrop-blur-md px-4 py-2 rounded-full border border-white/10 flex gap-4 text-xs font-mono text-gray-300 pointer-events-auto">
             <span>W: {config.walls.material}</span>
             <span className="text-gray-600">|</span>
             <span>F: {config.floor.type}</span>
          </div>
        </header>

        {/* 3D Viewport */}
        <div className="w-full h-full bg-gradient-to-b from-gray-900 to-black">
          <Preview3D config={config} />
        </div>
      </main>

      {/* RIGHT: CONFIGURATION SIDEBAR */}
      <aside className="w-[400px] z-30 shadow-2xl">
        <Controls 
          config={config} 
          setConfig={setConfig} 
          activeSection={activeSection}
          setActiveSection={setActiveSection}
          onGenerateAI={handleGenerateAI}
          isGenerating={isGenerating}
        />
      </aside>

      {/* AI RESULT MODAL */}
      {showAiModal && aiImage && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-8 animate-in fade-in duration-300">
           <div className="relative max-w-4xl w-full bg-gray-900 border border-gray-700 rounded-xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
              <div className="p-4 border-b border-gray-800 flex justify-between items-center bg-gray-800/50">
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                  <span className="text-purple-400">✨</span> Gemini Generated Render
                </h3>
                <div className="flex gap-2">
                   <a 
                     href={aiImage} 
                     download="elevator-design.png"
                     className="p-2 hover:bg-gray-700 rounded-full transition-colors"
                     title="Download"
                   >
                     <Download size={20} />
                   </a>
                   <button 
                     onClick={() => setShowAiModal(false)}
                     className="p-2 hover:bg-red-500/20 hover:text-red-400 rounded-full transition-colors"
                   >
                     <X size={20} />
                   </button>
                </div>
              </div>
              <div className="flex-1 overflow-auto flex items-center justify-center bg-black p-4">
                 <img src={aiImage} alt="AI Render" className="max-w-full max-h-[70vh] rounded shadow-lg object-contain" />
              </div>
              <div className="p-4 bg-gray-900 text-xs text-center text-gray-500">
                Generated by Gemini 3 Pro Vision. Results may vary.
              </div>
           </div>
        </div>
      )}

      {/* ERROR TOAST */}
      {error && (
        <div className="fixed bottom-6 left-6 z-50 bg-red-900/90 text-white px-6 py-4 rounded-lg shadow-xl border border-red-500/50 flex items-center gap-3">
           <div className="w-2 h-2 rounded-full bg-red-500 animate-pulse"></div>
           {error}
           <button onClick={() => setError(null)} className="ml-4 hover:text-red-200"><X size={14} /></button>
        </div>
      )}

    </div>
  );
};

export default App;
